"""adiciona atualizacoes de denuncia

Revision ID: 11fd44479061
Revises: 7da5dcc1bd3b
Create Date: 2026-08-27 14:20:48.087470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fd44479061'
down_revision = '7da5dcc1bd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AtualizacaoDenuncia',
    sa.Column('id_atualizacao', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_atualizacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AtualizacaoDenuncia')
    # ### end Alembic commands ###
