"""Criar sistema de pedidos SOS

Revision ID: 2701bd60828b
Revises: 
Create Date: 2026-08-11 14:13:00.936575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2701bd60828b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PedidoSOS',
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sos')
    )
    op.create_table('PedidoSOSContato',
    sa.Column('id_sos_contato', sa.Integer(), nullable=False),
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['ContatoEmergencia.id_contato'], ),
    sa.ForeignKeyConstraint(['id_sos'], ['PedidoSOS.id_sos'], ),
    sa.PrimaryKeyConstraint('id_sos_contato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PedidoSOSContato')
    op.drop_table('PedidoSOS')
    # ### end Alembic commands ###
