"""Estrutura inicial PostgreSQL

Revision ID: 5c72955c569f
Revises: 
Create Date: 2026-09-02 15:00:29.449982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c72955c569f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('user', 'admin', name='usuario_tipo_enum'), nullable=False),
    sa.Column('status_conta', sa.Enum('ativa', 'bloqueada', 'desativada', name='usuario_status_conta_enum'), nullable=False),
    sa.Column('aceitou_termos', sa.Boolean(), nullable=False),
    sa.Column('data_aceite_termos', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ContatoEmergencia',
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_contato')
    )
    op.create_table('Denuncia',
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('violencia_fisica', 'violencia_psicologica', 'violencia_sexual', 'assedio', 'ameaca', 'outro', name='denuncia_tipo_enum'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'finalizado', 'cancelado', name='denuncia_status_enum'), nullable=True),
    sa.Column('anonimo', sa.Boolean(), nullable=True),
    sa.Column('nivel_risco', sa.Enum('baixo', 'medio', 'alto', 'emergencia', name='denuncia_nivel_risco_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_denuncia')
    )
    op.create_table('PedidoSOS',
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tipo_encaminhamento', sa.String(length=30), nullable=True),
    sa.Column('data_encaminhamento', sa.DateTime(), nullable=True),
    sa.Column('observacao_encaminhamento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sos')
    )
    op.create_table('RecuperacaoConta',
    sa.Column('id_recuperacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recuperacao')
    )
    op.create_table('Arquivo',
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('imagem', 'video', 'documento', name='arquivo_tipo_enum'), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('Atendimento',
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    op.create_table('AtualizacaoDenuncia',
    sa.Column('id_atualizacao', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_atualizacao')
    )
    op.create_table('AtualizacaoSOS',
    sa.Column('id_atualizacao', sa.Integer(), nullable=False),
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_sos'], ['PedidoSOS.id_sos'], ),
    sa.PrimaryKeyConstraint('id_atualizacao')
    )
    op.create_table('Historico',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_table('Localizacao',
    sa.Column('id_localizacao', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_denuncia'], ['Denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_localizacao')
    )
    op.create_table('PedidoSOSContato',
    sa.Column('id_sos_contato', sa.Integer(), nullable=False),
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['ContatoEmergencia.id_contato'], ),
    sa.ForeignKeyConstraint(['id_sos'], ['PedidoSOS.id_sos'], ),
    sa.PrimaryKeyConstraint('id_sos_contato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PedidoSOSContato')
    op.drop_table('Localizacao')
    op.drop_table('Historico')
    op.drop_table('AtualizacaoSOS')
    op.drop_table('AtualizacaoDenuncia')
    op.drop_table('Atendimento')
    op.drop_table('Arquivo')
    op.drop_table('RecuperacaoConta')
    op.drop_table('PedidoSOS')
    op.drop_table('Denuncia')
    op.drop_table('ContatoEmergencia')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
