"""Adiciona aceite dos termos de uso

Revision ID: 7da5dcc1bd3b
Revises: cf3ba3daaf8f
Create Date: 2026-08-25 14:57:17.097356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da5dcc1bd3b'
down_revision = 'cf3ba3daaf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aceitou_termos', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('data_aceite_termos', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('data_aceite_termos')
        batch_op.drop_column('aceitou_termos')

    # ### end Alembic commands ###
