"""adiciona notificacoes sos

Revision ID: b1e47512b475
Revises: 11fd44479061
Create Date: 2026-08-31 15:06:35.850931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e47512b475'
down_revision = '11fd44479061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AtualizacaoSOS',
    sa.Column('id_atualizacao', sa.Integer(), nullable=False),
    sa.Column('id_sos', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_sos'], ['PedidoSOS.id_sos'], ),
    sa.PrimaryKeyConstraint('id_atualizacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AtualizacaoSOS')
    # ### end Alembic commands ###
